
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices_rating
  application:
    name: RATING-SERVICE
      
server:
  port: 8092
  
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
okta:
  oauth2:
    issuer: https://dev-07330456.okta.com/oauth2/default
    audience: api://default
    